RECORD_DELIM = b"\x01"
FIELD_DELIM = b"\x02"
HANDSHAKE_MESSAGE_DELIM = b"\x03"
MESSAGE_DELIM = b"\x08"
CLIENT_CONNECT = 0
CLIENT_POLL = 1
CLIENT_SEND = 2
CLIENT_CONNECT_FAST = 3
INITIAL_TOPIC_LOAD = 20
DELTA = 21
CLIENT_SUBSCRIBE = 22
CLIENT_UNSUBSCRIBE = 23
CLIENT_SWAP_SUBSCRIPTIONS = 26
NONE_ENCODING = 0
ENCRYPTED_ENCODING = 17
COMPRESSED_ENCODING = 18
BASE64_ENCODING = 19
SERVER_PING = 24
CLIENT_PING = 25
CLIENT_ABORT = 28
CLIENT_CLOSE = 29
ACK_ITL = 30
ACK_DELTA = 31
ACK_RESPONSE = 32

SUPPRESS_SERVER_MESSAGE = 1
BATCH = 2
SUPPRESS_FULL_HIERARCHY = 4
SUPPRESS_POP_FALLBACK = 8
NO_GRACE_PERIOD = 16
DONT_BATCH = 32
USE_CUSTOM_PARAMS = 64


HANDSHAKE_STATUS_CONNECTED = "100"
HANDSHAKE_STATUS_REJECTED = "111"
CONNECTION_TIMEOUT_LIMIT = 15e3
HANDSHAKE_TIMEOUT_LIMIT = 15e3
HANDSHAKE_PROTOCOL = 35
HANDSHAKE_VERSION = 3
HANDSHAKE_CONNECTION_TYPE = 80
HANDSHAKE_CAPABILITIES_FLAG = 1
TOPIC = '__time'

acts = {"F": 'SNAPSHOT',
"U": 'UPDATE',
"I": 'INSERT',
"D": 'SNAPSHOT'}

